name: GitHub Actions
on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
  schedule:
    - cron: '*/5 * * * *'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "executing automation script"
      - run: echo "checking network connectivity"
      - run: curl https://gorest.co.in/public/v2/users
      - run: echo "The name of your branch is ${{ github.ref }}"
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: ls -l
      - run: docker run -it --rm veracode/pipeline-scan:cmd --file scriptedsql-connector-1.5.20.3.jar
